version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: DatabaseName
      MYSQL_USER: MySQLNormalUser
      MYSQL_PASSWORD: MySQLNormalPassword

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - "./wordpress:/var/www/html"
      - "./themes:/var/www/html/wp-content/themes"
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: DatabaseName
      WORDPRESS_DB_PASSWORD: MySQLNormalUser
      WORDPRESS_DB_NAME: DatabaseName
volumes:
  db_data: {}
  wordpress_data: {}