version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MySQLRootPassword
      MYSQL_DATABASE: DatabaseName
      MYSQL_USER: MySQLNormalUser
      MYSQL_PASSWORD: MySQLNormalPassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - "./wordpress:/var/www/html"
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: MySQLRootPassword
      WORDPRESS_DB_NAME: DatabaseName

volumes:
  db_data: { }
  wordpress_data: { }
